### ISSUE TITLE
DC-DC converter breakout

### ISSUE THREAD

**Issue by dwaq** [ZeroPhone/BreakoutPCBMockups#1]
What else needs done for this part?

I see the 3D model for the inductor is missing. Should I model that from scratch or it is a common shape?

The model is set to "Inductors.3dshapes/Inductor_Taiyo-Yuden_NR-60xx.wrl" but I don't have that on my system.

**Comment by CRImier** [comment]
Hi! Yes, the inductor (basically, a 6.5x6.5x2.7mm block) needs to be modelled, but that's it for this part - I'll take care of the placement. The current 3D shape (doesn't show for me either) is most likely wrong anyway, as was the footprint.

**Comment by dwaq** [comment]
OK, I'll design the 3D shape and link it into the PCB and you can move it into place.

**Comment by dwaq** [comment]
Created model based on your provided dimensions and linked to PCB. See #2 for details.
